services:
  postgres:
    image: postgres:15-alpine
    container_name: finanzen-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=finanzen-api
      - POSTGRES_HOST_AUTH_METHOD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: