-- V1__create_categories_and_transactions_tables.sql

-- Tabela de Categorias
CREATE TABLE tb_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL UNIQUE, -- Nome da categoria, não nulo e único
    description VARCHAR(255),          -- Descrição da categoria (opcional)
    PRIMARY KEY (id)
);

-- Tabela de Transações
CREATE TABLE tb_transactions (
     BIGINT GENERATED BY DEFAULT AS IDENTITY,
     description VARCHAR(255) NOT NULL,            -- Descrição da transação
     amount NUMERIC(10,2) NOT NULL,               -- Valor monetário (ex: 12345678.90)
     transaction_date TIMESTAMP(6) NOT NULL,      -- Data e hora da transação
     transaction_type VARCHAR(255) NOT NULL CHECK (transaction_type IN ('INCOME', 'EXPENSE')), -- Tipo: Receita ou Despesa
     category_id BIGINT NOT NULL,                 -- Chave estrangeira para a categoria
     PRIMARY KEY (id)
);

-- Adiciona a chave estrangeira para a tabela de transações
ALTER TABLE tb_transactions
    ADD CONSTRAINT fk_transaction_category -- Nome da restrição de chave estrangeira
    FOREIGN KEY (category_id)
    REFERENCES tb_categories (id);